aliases:
  - &docker_worker
    - image: circleci/golang:1.11
  - &install_deps
    name: Installing dependencies
    command: go get -v -t -d ./...
  - &lint
    name: Linting
    command: go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
  - &test
    name: Run Unit Tests 
    command: go test -v ./...
version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - development
    docker: *docker_worker
    working_directory: /go/src/github.com/aeternas/docker-watchdog
    steps:
      - checkout
      - run: *install_deps
      - run: *lint
      - run: *test
