aliases:
  - &docker_worker
    - image: circleci/golang:1.12
  - &install_deps
    name: Installing dependencies
    command: go get -v -t -d ./...
  - &lint
    name: Install & Execute linter
    command: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest && \
        golangci-lint run
  - &test
    name: Run Unit Tests 
    command: go test -v ./...
version: 2.1
jobs:
  build:
    docker: *docker_worker
    working_directory: /go/src/github.com/aeternas/docker-watchdog
    steps:
      - checkout
      - run: *install_deps
      - run: *lint
      - run: *test
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
